name: firstore_curd
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  lottie: ^1.4.0
  get: 4.6.5
  cloud_firestore: ^3.4.4
  firebase_auth: ^3.6.3
  flutter_screenutil: ^5.5.3+2
  google_fonts: ^2.2.0
  firebase_core:
  expandable_text: ^2.3.0

  flutter: 
    sdk: flutter
  flutter_gravatar: ^2.0.2
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

